export default {
  en: {
    dir: "ltr",
    availableText: "This page is also available in:",
    skipText: "Jump to main content",
    ariaPrimary: "Primary",
    ariaLang: "Change language",
    home: "Home",
    no_content: "No posts to show",
    human: "If you are a human, ignore this field",
    name: "Name",
    email: "Email",
    email_reply: "(optional, only if you want a reply)",
    message: "Message",
    send: "Send",
    contact: "Contact",
    dark_light: "Toggle between dark/light mode",
    footer: {
      created_with: "Site created with",
      by_me: "by Jens Andreasson",
      published: "Published on",
    }
  },
  sv: {
    dir: "ltr",
    availableText: "Den här sidan finns även på:",
    skipText: "Hoppa till sidans huvudinnehåll",
    ariaPrimary: "Primär",
    ariaLang: "Byt språk",
    home: "Hem",
    no_content: "Inga inlägg att visa",
    human: "Om du är en människa så lämna detta fält tomt",
    name: "Namn",
    email: "E-post",
    email_reply: "(valfritt, endast om du vill ha ett svar)",
    message: "Meddelande",
    send: "Skicka",
    contact: "Kontakt",
    dark_light: "Växla mellan mörkt/ljust läge",
    footer: {
      created_with: "Sidan är skapad med",
      by_me: "av Jens Andreasson",
      published: "Publicerad på",
    }
  },
}
