export default {
  keyWords: [
    "backend",
    "frontend",
    "js",
    "javascript",
    "git",
    "github",
    "webbutveckling",
    "programmering",
    "gymnasieskola",
    "skola",
  ],
  siteDesc: "J.Anteckningar är en blogg om webbutveckling, programmering och skola.",
  author: {
    name: "Jens Andreasson",
    email: "jensandreasson77@gmail.com",
    url: "https://jensa.dev",
    github: "jensadev",
  },
  url: process.env.URL || "http://localhost:8080",
  time: Date.now(),
  theme: "#ff0f54",
  siteName: "J.Anteckningar",
}