module.exports = {
  siteName: "J.Anteckningar",
  siteDesc: "Blog, projekt och anteckningsblock för Jens Andreasson",
  keyWords: [
    "blog",
    "html",
    "jens",
    "andreasson",
    "jensadev",
    "teacher",
    "html",
    "web",
    "css",
    "js",
    "javascript",
    "webbutveckling",
    "programmering",
  ],
  author: {
    name: "Jens Andreasson",
    email: "jensandreasson77@gmail.com",
    url: "https://jensa.dev",
    github: "jensadev",
  },
  url: process.env.URL || "http://localhost:8080",
  time: Date.now(),
  locale: "sv-SE",
  lang: "sv",
  theme: "#2d303c",
}
