module.exports = {
  siteName: "J.Anteckningar",
  siteDesc:
    "Blog, projekt, resurser och anteckningsblock för Jens Andreasson. Innehåll kopplat till teknikämnen inom gymnasieskolan. Främst programmering och webbutveckling.",
  keyWords: [
    "blog",
    "html",
    "jens andreasson",
    "jensadev",
    "teacher",
    "html",
    "web",
    "web development",
    "learn web development",
    "programming",
    "css",
    "pedagogik",
    "front end development",
    "back end development",
    "js",
    "javascript",
    "git",
    "github",
    "webbutveckling",
    "programmering",
    "gymnasieskola",
    "skola",
  ],
  author: {
    name: "Jens Andreasson",
    email: "jensandreasson77@gmail.com",
    url: "https://jensa.dev",
    github: "jensadev",
  },
  url: process.env.URL || "http://localhost:8080",
  time: Date.now(),
  locale: "sv-SE",
  lang: "sv",
  theme: "#ff0f54",
}
